const jobs=[
 {id:13,initials:'SR',tone:'green',title:'Cashier — age fit not published',company:'ShopRite of Garwood',location:'Garwood, NJ',distance:'Approx. 1.7 miles away',pay:'$15.92–$16.99/hr',hours:'Hours not published',schedule:['after-school','weekend'],time:'Schedule not published',age:'Confirm with employer',summary:'Customer checkout and service role listed on ShopRite of Garwood’s official current-opportunities page.',publicListing:true,sourceUrl:'https://cta.cadienttalent.com/index.jsp?LOCATION_ID=41379753696&SEQ=locationDetails&applicationName=ShopRiteNonReqExt&locale=en_US',checked:'Aug 18, 2026',sourceLabel:'Official employer opportunities page',sourceNote:'The Garwood store currently lists cashier and several other roles with pay ranges. The posting page does not state minimum age or weekly hours. This is included as a lead, not as confirmed student eligibility; ask the employer before applying.'},
 {id:14,initials:'Y',tone:'blue',title:'Aftercare Counselor',company:'Westfield Area YMCA',location:'Garwood, NJ',distance:'Approx. 1.5 miles away',pay:'$16.00–$18.50/hr',hours:'Part-time · exact hours not published',schedule:['after-school'],time:'After-school program',age:'16+',summary:'Support children in a school-age aftercare program. The YMCA’s current careers board lists aftercare roles in Garwood and Cranford.',publicListing:true,sourceUrl:'https://recruiting.paylocity.com/recruiting/jobs/All/a2010de4-50c9-427c-bb70-e3460002a1a0/YMCA-of-Westfield-NJ',checked:'Aug 18, 2026',sourceLabel:'Official employer board + public role details',sourceNote:'The official YMCA board currently lists the Garwood aftercare opening. Public role details state age 16+ and $16.00–$18.50 per hour. Exact weekly hours were not published; confirm they fit the 10–20 hour pilot target.'},
 {id:15,initials:'M',tone:'amber',title:'Retail Service Team Member',company:'Michaels',location:'Clark, NJ',distance:'Approx. 4.5 miles away',pay:'$16.25–$19.10/hr',hours:'Hours not published',schedule:['after-school','weekend'],time:'Schedule not published',age:'16+',summary:'Customer service and store-support work at the Clark location. Current public results state that this role requires team members to be at least 16.',publicListing:true,sourceUrl:'https://www.indeed.com/q-part-time-jobs-for-16-year-olds-l-westfield%2C-nj-jobs.html',checked:'Aug 18, 2026',sourceLabel:'Third-party listing · employer-provided details',sourceNote:'The current public listing identifies the Clark location, pay range and age-16 requirement. A stable direct URL to the exact employer application was not available. Confirm the role and schedule remain open.'},
 {id:16,initials:'A',tone:'green',title:'Server / Waitstaff — age fit not published',company:'Atria Cranford',location:'Cranford, NJ',distance:'Approx. 1.8 miles away',pay:'$15.92–$19.10/hr',hours:'Part-time · exact hours not published',schedule:['after-school','weekend'],time:'Schedule not published',age:'Confirm with employer',summary:'Part-time dining-service role at the Atria senior-living community in Cranford.',publicListing:true,sourceUrl:'https://atriacareers.com/careers/server-waitstaff-2026-278590/',checked:'Aug 18, 2026',sourceLabel:'Official employer careers page',sourceNote:'Atria’s official posting identifies this as a current part-time Cranford role and publishes the pay range. It does not state minimum age or weekly hours. Confirm student eligibility and duties before applying.'},
 {id:7,initials:'DD',tone:'amber',title:'Crew Member (Age 16+)',company:'NATC Donuts / Dunkin’',location:'Cranford, NJ',distance:'Approx. 1 mile away',pay:'Not specified',hours:'Part-time · hours not specified',schedule:[],time:'Flexible availability requested',age:'16+',summary:'Guest service, cashier transactions, preparing products, restocking, and maintaining a clean work area. Some equipment may have additional minimum-age requirements.',publicListing:true,sourceUrl:'https://corporate.natcdonuts.com/job_applications/apply_external/843?return=%2Fjobs%2Findex_external',checked:'Aug 18, 2026',sourceLabel:'Official employer source',sourceNote:'The official employer page explicitly says age 16+ and accepts part-time availability. Pay and exact hours were not published. This opening has not been verified directly with the employer.'},
 {id:8,initials:'QC',tone:'blue',title:'Minor Team Member',company:'QuickChek',location:'Cranford, NJ',distance:'Approx. 1 mile away',pay:'$15.60–$16.10/hr',hours:'Part-time · exact hours not specified',schedule:['after-school','weekend'],time:'Flexible schedule advertised',age:'16–17',summary:'Customer service, cash handling, food preparation, stocking, cleaning, and maintaining an orderly store. Responsibilities and available hours may be limited by age.',publicListing:true,sourceUrl:'https://www.monster.com/job-openings/minor-team-member-cranford-nj--870329ec-d60d-469c-a4ef-217244b613a7',checked:'Aug 18, 2026',sourceLabel:'Third-party listing · check employer careers page',sourceNote:'This third-party posting specifically describes a Cranford position for ages 16–17. QuickChek’s official careers portal is active, but a stable direct employer URL for this exact opening was not available. Confirm availability before applying.'},
 {id:9,initials:'SY',tone:'green',title:'Local team member — role not specified',company:'Soft N’ Yummy',location:'Cranford, NJ',distance:'Approx. 1.6 miles away',pay:'Not published',hours:'Flexible scheduling advertised',schedule:['after-school','weekend'],time:'Schedule arranged with employer',age:'Age not published',summary:'The Cranford dessert shop has an active “Join Our Team” page seeking friendly, energetic team members for customer service in a fast-paced environment.',publicListing:true,sourceUrl:'https://softnyummy.com/careers/',checked:'Aug 18, 2026',sourceLabel:'Official employer application',sourceNote:'The employer’s own careers page is accepting applications and advertises flexible scheduling. It does not publish pay, weekly hours, minimum age, or exact duties. Students should confirm all four before accepting an interview or shift.'},
 {id:10,initials:'M',tone:'amber',title:'Crew Team Member (Age 16+)',company:'McDonald’s',location:'Garwood, NJ',distance:'Approx. 1.4 miles away',pay:'Not published',hours:'Part-time or full-time offered',schedule:['weekend'],time:'Day shift · weekends as needed',age:'16+',summary:'Customer service and restaurant crew work at the nearby Garwood franchise. The posting explicitly welcomes applicants age 16+ and offers flexible scheduling.',publicListing:true,sourceUrl:'https://www.indeed.com/viewjob?jk=6d1fa3b75f35517e',checked:'Aug 18, 2026',sourceLabel:'Public franchise listing',sourceNote:'This is a current public posting for the Garwood restaurant, not Cranford. It includes part-time and full-time options; students should request a 10–20 hour schedule and confirm that assigned equipment is permitted for workers under 18.'},
 {id:11,initials:'5B',tone:'blue',title:'Sales Associate (Age 16+)',company:'Five Below',location:'Clark, NJ',distance:'Approx. 4.5 miles away',pay:'From $15.92/hr',hours:'Part-time · exact hours not published',schedule:['after-school','weekend'],time:'Flexible schedule advertised',age:'16+',summary:'Customer service, checkout, recovery, stocking light merchandise, and maintaining store presentation at the nearby Clark location.',publicListing:true,sourceUrl:'https://www.indeed.com/q-five-below-l-clark%2C-nj-jobs.html',checked:'Aug 18, 2026',sourceLabel:'Third-party listing · employer-provided details',sourceNote:'The posting identifies the Clark store, part-time status, starting pay, flexible scheduling, and age 16+. It may require an Indeed account before forwarding to the company application. Confirm the listing remains open before applying.'},
 {id:12,initials:'DD',tone:'amber',title:'Crew Member (Age 16+)',company:'NATC Donuts / Dunkin’',location:'Garwood, NJ',distance:'Approx. 1.5 miles away',pay:'Not published',hours:'Part-time · exact hours not published',schedule:['after-school','weekend'],time:'Extremely flexible hours advertised',age:'16+',summary:'Guest service, cashier transactions, preparing products, restocking, and maintaining a clean work area at a nearby NATC-operated Dunkin’ location.',publicListing:true,sourceUrl:'https://corporate.natcdonuts.com/jobs/index_external',checked:'Aug 18, 2026',sourceLabel:'Official employer opportunities page',sourceNote:'NATC’s official page lists age-16+ crew opportunities and Garwood appears in current public job results. The employer does not publish pay or guaranteed weekly hours. Confirm the selected application is for Garwood and that duties are age-appropriate.'},
];

const list=document.querySelector('#job-list'),count=document.querySelector('#result-count'),search=document.querySelector('#search');
let activeFilter='all';
const savedJobs=new Set();
function renderJobs(){
 const query=search.value.trim().toLowerCase();
 const visible=jobs.filter(j=>(activeFilter==='all'||j.schedule.includes(activeFilter))&&`${j.title} ${j.company} ${j.location} ${j.summary}`.toLowerCase().includes(query));
 list.innerHTML=visible.map(j=>`<article class="job-card" tabindex="0" data-id="${j.id}" aria-label="View ${j.title} at ${j.company}"><div class="company-logo ${j.tone}">${j.initials}</div><div><span class="public-label">Public listing · not employer verified</span><h3>${j.title}</h3><p>${j.company}<br><strong class="job-location">${j.location} · ${j.distance}</strong></p><div class="job-meta"><span class="public-source">${j.sourceLabel} · Checked ${j.checked}</span><span>${j.time}</span><span>${j.age}</span></div></div><div class="pay"><strong>${j.pay}</strong><span>${j.hours}</span></div><button class="save-job ${savedJobs.has(j.id)?'saved':''}" data-save="${j.id}" aria-label="${savedJobs.has(j.id)?'Remove from saved jobs':'Save job'}" aria-pressed="${savedJobs.has(j.id)}">${savedJobs.has(j.id)?'♥':'♡'}</button></article>`).join('');
 count.textContent=visible.length;document.querySelector('#empty-state').classList.toggle('hidden',visible.length!==0);
 document.querySelectorAll('.job-card').forEach(card=>{card.addEventListener('click',e=>{if(!e.target.closest('.save-job'))openJob(+card.dataset.id)});card.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.target.closest('.save-job'))openJob(+card.dataset.id)})});
 document.querySelectorAll('.save-job').forEach(btn=>btn.addEventListener('click',()=>{const id=+btn.dataset.save;if(savedJobs.has(id)){savedJobs.delete(id);toast('Removed from saved jobs.')}else{savedJobs.add(id);toast('Job saved.')}renderJobs()}));
}
document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;renderJobs()}));
search.addEventListener('input',renderJobs);

document.querySelector('[data-back-to-jobs]').addEventListener('click',()=>showView('jobs'));
document.querySelector('[data-back-to-jobs]').addEventListener('click',()=>showView('jobs'));
document.querySelectorAll('.nav-link').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('[data-back-to-jobs]').addEventListener('click',()=>showView('jobs'));
document.querySelector('[data-back-to-jobs]').addEventListener('click',()=>showView('jobs'));
document.querySelectorAll('.nav-link').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelector(`#${btn.dataset.view}`).classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'})}));

const modal=document.querySelector('#job-modal');
function openJob(id){const j=jobs.find(x=>x.id===id);document.querySelector('#modal-content').innerHTML=`<span class="public-label">Public listing · not employer verified</span><div class="modal-head"><div class="company-logo ${j.tone}">${j.initials}</div><div><p class="eyebrow">${j.company}</p><h2>${j.title}</h2><span class="public-source">${j.sourceLabel} · Checked ${j.checked}</span></div></div><p>${j.summary}</p><div class="detail-grid"><div><span>Location</span><strong>${j.location}<br>${j.distance}</strong></div><div><span>Pay</span><strong>${j.pay}</strong></div><div><span>Weekly hours</span><strong>${j.hours}</strong></div><div><span>Schedule</span><strong>${j.time}</strong></div><div><span>Minimum age</span><strong>${j.age}</strong></div></div><div class="modal-note"><strong>Why this listing is shown</strong><br>${j.sourceNote}</div><div class="modal-actions"><a class="primary-btn source-link" href="${j.sourceUrl}" target="_blank" rel="noopener">View original listing</a></div>`;modal.showModal()}
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});

const form=document.querySelector('#job-form');
document.querySelector('#start-post').addEventListener('click',()=>{form.classList.remove('hidden');form.scrollIntoView({behavior:'smooth'})});
document.querySelector('.close-form').addEventListener('click',()=>form.classList.add('hidden'));
form.addEventListener('submit',e=>{e.preventDefault();form.reset();form.classList.add('hidden');toast('Job submitted for safety review.')});
document.querySelector('.text-btn').addEventListener('click',()=>toast('Profile editor would open here.'));
document.querySelector('.avatar').addEventListener('click',()=>toast('Signed in as Jordan, age 17.'));
const tipDialog=document.querySelector('#tip-modal');
document.querySelectorAll('[data-share-tip]').forEach(button=>button.addEventListener('click',()=>tipDialog.showModal()));
document.querySelector('.tip-close').addEventListener('click',()=>tipDialog.close());
document.querySelector('#tip-form').addEventListener('submit',event=>{event.preventDefault();event.currentTarget.reset();tipDialog.close();toast('Thanks — this lead is queued for verification.')});
tipDialog.addEventListener('click',event=>{if(event.target===tipDialog)tipDialog.close()});
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}

// Town-first prototype routing. School entry pages reuse the town marketplace.
function showView(id,schoolEntry=false){
 document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));
 document.querySelector('#'+id).classList.add('active-view');
 const local=id!=='platform';
 document.querySelector('#platform-nav').classList.toggle('hidden',local);
 document.querySelector('#market-nav').classList.toggle('hidden',!local);
 document.querySelector('.avatar').classList.toggle('hidden',!local);
 document.querySelector('#school-entry-banner').classList.toggle('hidden',!schoolEntry);
 document.querySelector('[data-back-to-jobs]').addEventListener('click',()=>showView('jobs'));
document.querySelector('[data-back-to-jobs]').addEventListener('click',()=>showView('jobs'));
document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));
 window.scrollTo({top:0,behavior:'smooth'});
}
function route(){const path=location.hash.replace(/^#/,'')||'/';if(path==='/cranford')showView('jobs');else if(path==='/schools/cranford-high')showView('jobs',true);else showView('platform')}
function enterCranford(){location.hash='/cranford'}
document.querySelector('#location-form').addEventListener('submit',e=>{e.preventDefault();const v=document.querySelector('#town-search').value.trim().toLowerCase();if(v.includes('cranford')||v.replace(/\s/g,'')==='07016')enterCranford();else toast('Cranford, NJ is the available prototype location.')});
document.querySelector('[data-cranford]').addEventListener('click',enterCranford);
document.querySelector('[data-home]').addEventListener('click',()=>location.hash='/');
document.querySelector('[data-normal-town]').addEventListener('click',enterCranford);
document.querySelectorAll('[data-register]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#profile-modal').showModal()));
document.querySelector('.profile-close').addEventListener('click',()=>document.querySelector('#profile-modal').close());
document.querySelector('#profile-form').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#profile-modal').close();toast('Profile saved. School remains optional.')});
document.querySelector('[data-enter-employer]').addEventListener('click',()=>{enterCranford();setTimeout(()=>showView('employer'),0)});
document.querySelector('[data-audience-chooser]')?.addEventListener('click',()=>document.querySelector('#audience-modal').showModal());
document.querySelector('.audience-close').addEventListener('click',()=>document.querySelector('#audience-modal').close());
document.querySelector('[data-audience-student]').addEventListener('click',()=>{document.querySelector('#audience-modal').close();document.querySelector('#profile-modal').showModal()});
document.querySelector('[data-audience-employer]').addEventListener('click',()=>{document.querySelector('#audience-modal').close();enterCranford();setTimeout(()=>showView('employer'),0)});
window.addEventListener('hashchange',route);

renderJobs();route();
